class ExceptionTest01 {
	public static void div(int a, int b) {
		try
		{
			
		}
		catch (ArithmeticException)
		{
		}
	public static void main(String[] args) {
		div(4, 0)
	}
}
